site_name: 'PlexTrac Management Utility Docs'
site_url: https://docs.plextrac.ninja/code/plextrac-management-utility/
copyright: Copyright &copy; 2021 PlexTrac
dev_addr: 0.0.0.0:8000

plugins:
  - search
  - awesome-pages:
     filename: .nav
     collapse_single_pages: true

markdown_extensions:
  # MkDocs for material design reference for how to use this stuff
  #   https://squidfunk.github.io/mkdocs-material/reference
  # Docs on PyMdown Extensions: https://facelessuser.github.io/pymdown-extensions
  - pymdownx.highlight:
      guess_lang: True
  - pymdownx.inlinehilite:
      style_plain_text: true
  - pymdownx.snippets:
      base_path:
        - '.'
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink:
      repo_url_shortener: True
      repo_url_shorthand: True
      user: PlexTrac
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.critic:
      mode: view
  - smarty
  - admonition
  - toc:
      permalink: True
  - sane_lists
  - meta
  - md_in_html

theme:
  name: material
  features:
    - header.autohide
    - navigation.instant
    #- navigation.indexes # incompatible with toc.integrate
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - tags
    - toc.integrate
    - content.tabs.link
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
